import moo from 'moo';

export const lexer = moo.compile({
  ws: /[ \t]+/,
  asterisk: '*',
  create: 'create',
  index: 'index',
  table: 'table',
  select: 'select',
  where: 'where',
  update: 'update',
  insert: 'insert',
  using: 'using',
  batch: 'batch',
  set: 'set',
  and: 'and',
  on: 'on',
  like: 'like',
  drop: 'drop',
  alter: 'alter',
  from: 'from',
  delete_: 'delete',
  word: /[a-zA-Z0-9]+/,
  quotationWord: /"[a-zA-Z]+"/,
  quotationWordNumber: /"[a-zA-Z0-9]+"/,
  lparen: '(',
  rparen: ')',
  lBracket: '[',
  rBracket: ']',
  lcBracket: '{',
  rcBracket: '}',
  comma: ',',
  dot: '.',
  colon: ':',
  semiColon: ';',
  equal: '=',
  bigger: '>',
  smaller: '<',
  biggerEqual: '>=',
  smallerEqual: '<=',
});
