export const Messages = {
  accepted: '接受成功。',
  alreadyUploaded: '文件已上传。',
  apiKeyCreated: 'API 密钥创建成功。',
  apiKeyDeleted: 'API 密钥删除成功。',
  avatarRemoved: '头像移除成功。',
  avatarUploaded: '头像上传成功。',
  billingUpdated: '账单信息更新成功。',
  buildSucceeded: '构建成功。',
  cacheCleared: '缓存清除成功。',
  cancel2FA: '两步验证已取消。',
  chunksUploaded: '所有分片已接收，上传完成。',
  confirmUploaded: '上传文件已确认。',
  connected: '连接成功。',
  copied: '复制成功。',
  created: '创建成功。',
  cronRun: '任务执行成功。',
  cronScheduled: '任务调度成功。',
  default: '获取成功。',
  deleted: '删除成功。',
  delivered: '投递成功。',
  deploySucceeded: '部署成功。',
  disconnected: '断开连接成功。',
  emailSent: '邮件发送成功。',
  encryptionDisabled: '加密已禁用。',
  encryptionEnabled: '加密已启用。',
  exported: '导出成功。',
  fetched: '获取成功。',
  generatePDF: 'PDF 生成成功。',
  imported: '导入成功。',
  invitationSent: '邀请已发送。',
  licenseActivated: '许可证已激活。',
  licenseDeactivated: '许可证已停用。',
  listed: '列表获取成功。',
  loggedIn: '登录成功。',
  loggedOut: '登出成功。',
  migrationCompleted: '迁移完成。',
  moved: '移动成功。',
  onboardingComplete: '入职完成。',
  passwordChanged: '密码修改成功。',
  paymentProcessed: '支付已处理成功。',
  permissionGranted: '权限已授予。',
  permissionRevoked: '权限已撤销。',
  profileUpdated: '个人资料更新成功。',
  rateLimitedReset: '速率限制已重置。',
  refundProcessed: '退款已处理成功。',
  rejectedSuccess: '拒绝成功。',
  restored: '恢复成功。',
  restorePointCreated: '还原点创建成功。',
  roleAssigned: '角色分配成功。',
  roleRemoved: '角色移除成功。',
  saved: '保存成功。',
  sent: '发送成功。',
  sentUnlock: '解锁请求发送成功。',
  setup2FA: '两步验证已设置成功。',
  subscribed: '订阅成功。',
  syncCompleted: '同步完成。',
  test: '测试成功。',
  tokenIssued: '令牌已颁发。',
  tokenRevoked: '令牌已撤销。',
  unlock: '解锁成功。',
  unsubscribed: '取消订阅成功。',
  updated: '更新成功。',
  uploaded: '上传成功。',
  verified: '验证成功。',
  verify2FA: '两步验证已验证成功。',
  wallpaperUpdated: '壁纸更新成功。',
  webhookRegistered: 'Webhook 注册成功。',
  webhookUnregistered: 'Webhook 注销成功。',
};
