export const DefaultMsg = {
  FAIL: {
    default: 'Something went wrong. Try again later.',
    checkHash: 'Check hash failed.',
    credentials: 'Invalid credentials.',
    generatePDF: 'Failed to generate PDF.',
    invalidToken: 'Invalid token or token has expired.',
    mergeUpload: 'Merge failed, missing file slices.',
    noFileUploaded: 'No file uploaded.',
    setup2FA: '2FA is already set up for this account.',
    missingKeys: 'Missing key(s): ',
  },
  LOCKED: {
    beenLocked: 'Your account has been locked.',
    manyAttempt: 'Too many failed attempts. Please try again later.',
  },
  NOT_FOUND: {
    data: 'Resource not found.',
    file: 'File not found.',
  },
  SUCCESS: {
    default: 'Successfully retrieved.',
    alreadyUploaded: 'Successfully already uploaded.',
    cancel2FA: 'Successfully cancel 2FA.',
    chunksUploaded: 'Received all chunks. Successfully uploaded.',
    confirmUploaded: 'Successfully confirmed uploaded file.',
    deleted: 'Successfully deleted.',
    generatePDF: 'Successfully generate PDF.',
    sentUnlock: 'Successfully sent unlock request.',
    setup2FA: 'Successfully set up 2FA.',
    unlock: 'Successfully unlock.',
    uploaded: 'Successfully uploaded.',
    verify2FA: 'Successfully verified 2FA.',
  },
  UPLOAD: {
    CHUNK_ALREADY_EXISTS: 'Chunk already exists.',
    NO_FILE_PROVIDED: 'No file provided.',
    ONLY_ZIP_AND_RAR_ALLOWED: 'Only zip and rar files are allowed.',
    PATH_OR_TITLE_ALREADY_EXISTS: 'The path or the title already exists.',
    REQUIRE_TITLE_PATH: 'Query requires title or path.',
  },
};
